### ISSUE TITLE
suggestion to simplify writing to csv

### ISSUE THREAD

**Issue by ejohnson-amerilife** [evangambit/JsonOfCounties#1]
Thank you for your excellent work!

I have one suggestion that may simplify the way you convert the json to csv. It does require the additional overhead of importing pandas, but hopefully the benefits of readability and maintenance out way that small cost.
Here is an example (note that not all of the columns that contain dictionaries are included e.g. "covid-deaths" is not included):

```
import pandas as pd
df_county = pd.read_json('https://raw.githubusercontent.com/evangambit/JsonOfCounties/master/counties.json')

columns_with_dicts=[
    'age', 'noaa',
    'population', 'deaths', 'bls', 'fatal_police_shootings', 
    'elections', 'edu', 'cost-of-living', 'industry', 'health'
]
for col in columns_with_dicts:
    df_county = df_county.join(pd.json_normalize(df_county[col]).add_prefix(f'{col}.')).drop(
        columns=[col]
    )
    
df_county.to_csv('counties.csv', index=False)
```

**Comment by evangambit** [comment]
Sorry for the delayed response and thanks for the positive feedback!

Thanks for the suggestion. Done.

**Comment by ejohnson-amerilife** [comment]
Excellent! 
Just want to remind you that you'll have to add the names of **_all_** columns that contain dictionaries to the "columns_with_dicts" list, otherwise not all the data will be unpacked in the CSV.
Thanks again for the great work.

**Comment by ejohnson-amerilife** [comment]
Here is an automated approach to detect any column that contains a dict:
`columns_with_dicts = [i for i in df_county.columns if isinstance(df_county[i][0],dict)]`

So that would replace the code starting at:
https://github.com/evangambit/JsonOfCounties/blob/1db48489f62d1614123292f53b2256fa730d726c/create_json.py#L1373
